jaegertracing/helm-charts

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md

Testing gh actions for jaeger-operator chart README update. This needs to happen anyway, but I wanted to wait till GitHub Actions CI was set up and running before making PRs. This chart should pass CI.
Signed-off-by: Scott Rigby <scott@r6by.com>

Update Readme for jaeger-operator chart

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/agent-ds.yaml
charts/jaeger/values.yaml

It was not possible to change the --reporter.grpc.host-port to a custom hostname in case
the agent should send to a different service name.

Made it possible to overwrite --reporter.grpc.host-port flag

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/values.yaml
charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/values.yaml

Both Jaeger and Jaeger Operator have been released today under the version 1.16.0. This PR updates the charts to use the new versions.
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

Updated charts to use v1.16.0

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md

This makes managing the values in the values table much easier in an IDE, previously, each row tended to span across two lines in an IDE, now only very long ones do.

[jaeger] Trim whitespace in values table

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/query-deploy.yaml

As an immediate workaround to https://github.com/jaegertracing/jaeger/issues/1986
P.S. Also slipped in an if statement around query basepath, in case not set, no need to add this env var.

[jaeger] Add agent port env var

---

CNAME
_config.yml
index.md

Heavily inspired by @stefanprodan's  work for the Flux charts landing page, here is a PR to do this for Jaeger as well.
Is there a way of previewing this @scottrigby ?
We would need `charts.jaegertracing.io` added as a CNAME before merging
Would solve #6 
Signed-off-by: Naseem <naseemkullah@gmail.com>

Landing page

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/collector-svc.yaml
charts/jaeger/values.yaml

Collector will not listen Zipkin port without the environment variable.

Add env COLLECTOR_ZIPKIN_HTTP_PORT when collector.service.zipkinPort present

---

.github/workflows/release.yaml
charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/requirements.yaml
charts/jaeger/values.yaml
ct.yaml

Would solve #4
P.S. I also updated the README's helm install commands slightly... and removed some verbosity.
Also the condition moves form `provisionDataStore.elasticsearch` to the more standard `elasticsearch.enabled` , thoughts on that? We could do something similar once we use a different cassandra chart to depend on (https://github.com/bitnami/charts/tree/master/bitnami/cassandra seems like the best choice atm, but let's wait to see if Cassandra incubator chart gets hosted elsewhere)
Signed-off-by: Naseem <naseemkullah@gmail.com>

[jaeger] Use official elastic chart as elasticsearch dependency

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/_helpers.tpl
charts/jaeger/templates/agent-sa.yaml
charts/jaeger/templates/cassandra-schema-job.yaml
charts/jaeger/templates/cassandra-schema-sa.yaml
charts/jaeger/templates/collector-sa.yaml
charts/jaeger/templates/hotrod-sa.yaml
charts/jaeger/templates/query-sa.yaml
charts/jaeger/templates/spark-sa.yaml
charts/jaeger/values.yaml

When service accounts were originally added, the helm documentation regarding best practices on sa creation for multiple components was wrong. It has since been corrected and this approach follows the correct method
Signed-off-by: Naseem <naseemkullah@gmail.com>

[jaeger] refactor service accounts

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/crds/crd.yaml

CRD changes from [#802](https://github.com/jaegertracing/jaeger-operator/pull/802) should be merged into operator helm chart as currently the following errors are seen on logs:
```
time="2019-12-29T09:56:25Z" level=error msg="failed to store the running status into the current CustomResource" error="the server could not find the requested resource (put jaegers.jaegertracing.io jaeger-operator-jaeger)" execution="2019-12-29 09:56:24.974520864 +0000 UTC" instance=jaeger-operator-jaeger namespace=observability
time="2019-12-29T10:12:40Z" level=error msg="failed to store the running status into the current CustomResource" error="the server could not find the requested resource (put jaegers.jaegertracing.io jaeger-operator-jaeger)" execution="2019-12-29 10:12:40.637487009 +0000 UTC" …
```

[jaeger-operator]: update jaeger crd to include status resource

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/agent-ds.yaml
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/hotrod-deploy.yaml
charts/jaeger/templates/ingester-deploy.yaml
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/values.yaml

When deploying this chart in our cluster we found that we had to add security context to the deployments for them to run as non-root user.
So i created this PR where securityContext is added to the template/charts for deployment and its default value is provided in `values.yaml` file. These can be overwritten if someone uses jaeger chart as a dependency in their own values.yaml file.

[jaeger] Add security context to deployment charts in jaeger

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/_helpers.tpl
charts/jaeger/templates/spark-cronjob.yaml
charts/jaeger/values.yaml

- cassandra auth variables were missing in spark job
cmdlineParams were also missing
- fixed section {{- define "elasticsearch.client.url" -}} in helpers
it was generating wrong url

Added cassandra auth variables in spark job

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/_helpers.tpl

After #45 it is no longer possible to set an external elasticsearch host.

Allow to use external es host

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/values.yaml
charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/values.yaml

Signed-off-by: Naseem <naseem@transit.app>

Bump jaeger to 1.17.0

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/agent-ds.yaml
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/collector-svc.yaml
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/values.yaml

Hello.
My installation has some services landed outside the k8s cluster. Manually set a nodePort number for collector is important to bring agent's config valid over time.

[jaeger] Add ability to manually set nodeport for jaeger-collector

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/es-index-cleaner-sa.yaml

Chart version 0.22.0 has a bug:
If `.Values.esIndexCleaner.serviceAccount.create` is set to true to create a service account, the cleaner job fails to create a pod because no service account is created (as there is no template for the service account).

Add service accoiunt for es-index-cleaner object

---

.github/workflows/lint-test.yaml
.github/workflows/release.yaml

We've been experiencing https://github.com/actions/checkout/issues/23 quite a bit lately. v2 should fix that.

[ci] Use actions checkout v2

---

.github/workflows/lint-test.yaml
charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/_helpers.tpl
charts/jaeger/templates/agent-ds.yaml
charts/jaeger/templates/cassandra-schema-job.yaml
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/es-index-cleaner-cronjob.yaml
charts/jaeger/templates/ingester-deploy.yaml
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/templates/spark-cronjob.yaml
charts/jaeger/values.yaml

* cmd line options are templated as command arguments as they should be.
* components now have an env value to configure any env vars.
* Cassandra/Elasticsearch values that are required in the various components that talk to them (collector/ingester, query, spark-job, cassandra-schema, es-index-cleaner, however the latter three have non-standard env var names that are kept) have been moved to _helpers.tpl for shareability.

refactor-config

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/ingester-deploy.yaml
charts/jaeger/values.yaml
ct.yaml

Please see title.
Fixes any breakage related to jaegertracing/jaeger#2092 thus fixes https://github.com/jaegertracing/helm-charts/issues/61
cc @pavelnikolov @jpkrohling @arpitjindal97

[jaeger]Add kafka authentication option.

---

.github/workflows/lint-test.yaml

v2 has depth 1 by default. That’s why no changes are detected.
Signed-off-by: Naseem <naseem@transit.app>

Use checkout v2 but set depth to 0

---

.github/workflows/lint-test.yaml
.github/workflows/release.yaml
charts/jaeger/Chart.yaml
charts/jaeger/templates/agent-ds.yaml
charts/jaeger/templates/agent-svc.yaml
charts/jaeger/templates/cassandra-schema-job.yaml
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/collector-svc.yaml
charts/jaeger/templates/es-index-cleaner-cronjob.yaml
charts/jaeger/templates/hotrod-deploy.yaml
charts/jaeger/templates/hotrod-ing.yaml
charts/jaeger/templates/hotrod-svc.yaml
charts/jaeger/templates/ingester-deploy.yaml
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/templates/query-ing.yaml
charts/jaeger/templates/query-svc.yaml
charts/jaeger/templates/spark-cronjob.yaml

Use nindent function and indent the templating pipelines where the values will be, instead of indent function without indenting the templating pipelines to improve readability.

[jaeger]Use nindent over indent

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/query-svc.yaml
charts/jaeger/values.yaml

Currently a random node port number is generated for the Jaeger query service when using the NodePort service type. 
This pull request adds support for specifying the port number to use for the node port  for the Jaeger query service.

Added support for specifying the port number to use for the node port  for the Jaeger query service

---

charts/jaeger/Chart.yaml
charts/jaeger/requirements.yaml

Prior to this version, CRD ServiceMonitor was needed by default.

Update cassandra dependency chart version.

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/agent-ds.yaml
charts/jaeger/values.yaml

We do a lot of autoscaling in our cluster and have run into issues where the Jaeger agent pods end up stuck in `Pending` because other pods with the default priority filled the node before the agent pod could be scheduled. To prevent this, we added the ability to set the `priorityClassName` on the agent pods.

Allow setting of agent pod priorityClassName

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/hotrod-ing.yaml
charts/jaeger/templates/query-ing.yaml

Starting from Kubernetes version `1.16`, Ingress resource is no loger served from `extensions/v1beta1` apiVersion.
In this PR we migrate templates regarding these resources to newer and supported values.

Jaeger Chart: Migrate Ingress to non-deprecated apiVersion

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/_helpers.tpl
charts/jaeger/values.yaml

I was deploying Jeager with an Elasticsearch Backend. But I didn't use the elasticsearch Subchart but a custom chart, which supports the creation of Elastic related crds provided by the ECK Operator (https://github.com/elastic/cloud-on-k8s). When deploying an elasticsearch cluster via eck-operator there will be a secret created with the credentials for the elastic user. The difference is, that the credentials are stored under the .elastic key in the secret. To resolve this issue I added an Option to define the key within the referenced secret.

Add custom SecretKey Option for Elasticsearch

---

.github/workflows/lint-test.yaml
.github/workflows/release.yaml
charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/NOTES.txt
charts/jaeger/templates/_helpers.tpl
charts/jaeger/templates/agent-ds.yaml
charts/jaeger/templates/cassandra-schema-job.yaml
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/es-index-cleaner-cronjob.yaml
charts/jaeger/templates/ingester-deploy.yaml
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/templates/spark-cronjob.yaml
charts/jaeger/values.yaml
ct.yaml

fixes #120
fixes #124 
env was limited in its implementation, extraEnv takes a list and performs a toYaml to enable maxiumum flexibility such as values from secrets and configmaps
cc @cgroschupp @Jasstkn can you please review if you get a chance?

[jaeger] use extraEnv in favor of env

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/templates/role.yaml

On newer k8s clusters, the api group for ingresses has somehow changed. This should fix #112

[jaeger-operator] fix ingress role permissions

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/cassandra-schema-job.yaml
charts/jaeger/values.yaml

Similar to the existing deployment objects, this adds support for overriding the Cassandra schema job's securityContext.

Allow overriding the Cassandra schema job security context

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/values.yaml

We'd like to set a `priortiyClass` not only for the agents, but for the `Collector` and `Query-UI` as well.
This PR adds this possibility.
Signed-off-by: David Losert <david.losert@gmx.de>

[jaeger] Added PriorityClassName Configuration to Collector and Query

---

.github/workflows/release.yaml
.gitignore
charts/jaeger/Chart.yaml
charts/jaeger/requirements.yaml
charts/jaeger/values.yaml
ct.yaml

Resolves https://github.com/jaegertracing/helm-charts/issues/149
Incubator kafka chart will be obsolete soon as per these instructions: https://github.com/helm/charts#deprecation-timeline
Also liveness probe was failing for the incubator kafka chart.
Bitnami provides stable kafka chart that Jaeger's helm chart can use.

Use bitnami chart for kafka

---

charts/jaeger/Chart.yaml
charts/jaeger/values.yaml

Signed-off-by: Michael Lundquist <michaellundquist7@gmail.com>
Fixes commented out cassandra parameter format
#153 
Adding quotes to the cassandra.tls.enabled parameter so it can be passed correctly

[jaeger] Adding quotes to the cassandra.tls.enabled parameter

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/_helpers.tpl
charts/jaeger/templates/es-lookback-cronjob.yaml
charts/jaeger/templates/es-lookback-sa.yaml
charts/jaeger/templates/es-rollover-cronjob.yaml
charts/jaeger/templates/es-rollover-hook.yml
charts/jaeger/templates/es-rollover-sa.yaml
charts/jaeger/values.yaml

Signed-off-by: Vyacheslav Artemiev <v.artemiev@semrush.com>
Adds jobs to use the ES rollover feature https://www.jaegertracing.io/docs/1.19/deployment/#elasticsearch-rollover

[jaeger] Add elasticsearch rollover jobs

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/_helpers.tpl

Fixing how storage.cassandra.cmdlineParams and storage.elasticsearch cmdlineParams are parsed in storage.cmdArgs in _helpers.tpl.
- fixes #158

[jaeger] Fixing issue 158

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/es-rollover-sa.yaml

Signed-off-by: Vyacheslav Artemiev <v.artemiev@semrush.com>
- Rollover init hook tries to use a service account that has not yet been created

[jaeger] Fix ES rollover init job service account creation

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/NOTES.txt

Signed-off-by: Naseem <naseem@transit.app>
Cleans up the readme:
- With the `helm show values` command there is no need to duplicate values in the readme.
- Add note about es rollover requiring a pre existing Elasticsearch (@n4nn31355 can you please confirm?)
- Add note about Jaeger's recommendation for storage
- Add warning that storage should be explicitly configured, as the default settings are subject to change
- Reorganize sections

[jaeger] update readme and add recommendation to explicitly configure storage

---

charts/jaeger/Chart.yaml
charts/jaeger/requirements.yaml
charts/jaeger/templates/collector-ing.yaml
charts/jaeger/values.yaml

Add the option to enable ingress for the collector

[jaeger] Add the option to enable ingress for the collector

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/ingester-deploy.yaml
charts/jaeger/templates/query-deploy.yaml

Remove deployment strategy Recreate from all deployment templates to default to rolling updates.
- fixes #176

issue#176 [Jaeger] - Remove deployment strategy Recreate from all deployment templates 

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/agent-sa.yaml
charts/jaeger/templates/collector-sa.yaml
charts/jaeger/templates/query-sa.yaml
charts/jaeger/values.yaml

Adds ability to configure service account annotations for query, collector and agent. This can allow for example configure AWS IAM roles for service accounts.
Adds option to configure service account annotations for query, collector and agent.
- fixes #179

[jaeger] add option to configure service account annotations

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/agent-ds.yaml
charts/jaeger/templates/es-index-cleaner-cronjob.yaml
charts/jaeger/templates/es-lookback-cronjob.yaml
charts/jaeger/templates/es-rollover-cronjob.yaml
charts/jaeger/templates/spark-cronjob.yaml
charts/jaeger/values.yaml

- It adds concurrencyPolicy to all cronjob templates, so users can set them as they see fit. Kept the default value "Forbid" for backwards compatibility.
- Added Max Unavailable value to Jaeger agent daemonset (its default 1 and i kept it 1 in the values.yaml file).
- fixes #128

[jaeger] Add concurrencyPolicy to CronJob and maxUnavailable to jaeger-agent daemonset

---

charts/jaeger/Chart.yaml
charts/jaeger/values.yaml

- Sets default value for updateStrategy of the agent daemonset.

[jaeger] Make default value for daemonset updateStrategy an empty map {}

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/values.yaml

[jaeger-operator] Updated jaeger-operator to version 1.20.0

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/templates/NOTES.txt

Fix non-working export command in jaeger-operator `NOTES.txt`

[jaeger-operator] Add missing space to export command

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/elasticsearch-secret.yaml
charts/jaeger/templates/es-index-cleaner-cronjob.yaml
charts/jaeger/templates/es-lookback-cronjob.yaml
charts/jaeger/templates/es-rollover-cronjob.yaml
charts/jaeger/templates/es-rollover-hook.yml

This Pr is aimed at solving a couple of issues I encountered when installing jaeger elasticsearch jobs with a tls certificate mounted secret.
What happened before the PR was:
- extraSecretMounts in all elasticsearch cronjobs and rollover init hook were referenced as `volumeMounts` but not as `volumes`, leading to helm failing with errors like: `Job.batch "jaeger-store-es-rollover-init" is invalid: spec.template.spec.containers[0].volumeMounts[0].name: Not found: "jaeger-tls"` 
- the elasticsearch secret resource was created after the `es-rollover-init` job hook, hence causing it to hang while looking for that secret. ` Error: secret "jaeger-store-elasticsearch" not found`
Remediation was to:
- add the `volumes` field in all the cronjob and job resources with reference to …

[jaeger] Fixes elasticsearch jobs extraSecretMounts reference and secret resource creation.

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/query-ing.yaml
charts/jaeger/values.yaml

Adds configurable healthcheck to ingress
https://github.com/jaegertracing/jaeger-ui/issues/671

[jaeger] Add healthcheck to Jaeger query ingress

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/templates/deployment.yaml
charts/jaeger-operator/templates/jaeger.yaml
charts/jaeger-operator/templates/service.yaml
charts/jaeger-operator/values.yaml

For consistency, and those who use `helm template`, `namespace` was added in the `metadata` of the Deployment, service and jaeger.
For `jaeger`, it was given more flexibility to namespace it allowing to customize via `.Values.jaeger.namespace` otherwise will be defaulted to `.Release.Namespace`

feat(jaeger-operator): add namespace to Deplyment, service and jaeger templates

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/values.yaml

Updates the jaeger-operator image to v1.21.2.

[jaeger-operator] Updated jaeger-operator to version 1.21

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/crds/crd.yaml

This PRs fixes an issue which caused an error when installing the jaeger-operator chart due to an invalid CRD yaml.  
- fixes #193
I did test deployments to GKE 1.18.12-gke.1210 and K3D versions v1.16.15-k3s1, v1.18.15-k3s1, v1.20.2-k3s1.

[jaeger-operator]: fix invalid crd.yaml to conform to apiextensions.k8s.io/v1 CustomResourceDefinition schema

---

.github/PULL_REQUEST_TEMPLATE.md
charts/jaeger/Chart.yaml
charts/jaeger/templates/spark-cronjob.yaml

- Adds a `activeDeadlineSeconds` field to the Job template for the spark cronjob. This would help, if someone wants the job to terminate after X number of seconds.
https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-termination-and-cleanup
- Also Fixed DCO link to CONTRIBUTING.md

[jaeger] Add activeDeadlineSeconds field to Job template for the spark job

---

.github/workflows/lint-test.yaml
.github/workflows/release.yaml
charts/jaeger/Chart.yaml
charts/jaeger/values.yaml
ct.yaml

update jaeger to 1.22.0
also update elasticsearch subchart to latest 7.x

[jaeger] update to 1.22.0

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-deploy.yaml

Signed-off-by: Kristián Patlevič <patlevic.kristian@gmail.com>
Based on the change in the version [1.22.0](Remove deprecated CLI flags (#2751, @LostLaser)) it's changing the deprecated `COLLECTOR_ZIPKIN_HTTP_PORT` variable to new `COLLECTOR_ZIPKIN_HOST_PORT`.

[jaeger] Update deprecated COLLECTOR_ZIPKIN_HTTP_PORT variable

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/ingester-deploy.yaml

Signed-off-by: Chirag Tailor <ctailor2@gmail.com>
This adds serviceAccountName to the ingester deploy to ensure that pods managed by the deployment are associated with the service account that is either specified by the user or created by the helm chart.

[jaeger] Add serviceAccountName to ingester deploy

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/extra-list.yaml
charts/jaeger/values.yaml

This allows users to install extra kubernetes objects alongside this chart in the same fashion that many of the bitnami charts offer this capability. See the following bitnami charts for reference:
https://github.com/bitnami/charts/blob/master/bitnami/cassandra/values.yaml#L565
https://github.com/bitnami/charts/blob/master/bitnami/mariadb/values.yaml#L870
I would like this capability to exist in the jaeger helm chart to make it easier to manage pod security policies for the jaeger components as they are installed in my cluster.

[jaeger] Allow installing extra objects along with the chart

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/ingester-deploy.yaml

Pass `.Values.storage.kafka.brokers` through the `tpl` function in both usages to process the value as a template. Allowing template strings here makes it possible for users that provision kafka as part of the jaeger deployment to configure this value in the values yaml file rather than requiring it to be set via a flag. For installs that provision kafka without name overrides, the following template string should generally work here.
```yaml
storage:
kafka:
brokers:
- "{{ .Release.Name }}-kafka"
```

[jaeger] Allow template strings in kafka brokers value

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/_helpers.tpl
charts/jaeger/templates/agent-ds.yaml
charts/jaeger/templates/cassandra-schema-job.yaml
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/es-index-cleaner-cronjob.yaml
charts/jaeger/templates/es-lookback-cronjob.yaml
charts/jaeger/templates/es-rollover-cronjob.yaml
charts/jaeger/templates/hotrod-deploy.yaml
charts/jaeger/templates/ingester-deploy.yaml
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/values.yaml

Created a new Template variable that is used instead of `.Values.tag` in chart template files and it defaults to
`.Chart.AppVersion`
Makes a new helper template variable that is used for image tag in all template files. Default for that tag value is chart.appVersion (or it can be overridden by the users of the chart).
- fixes #185

[Jaeger] Make .Values.tag default to .Chart.AppVersion

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/spark-cronjob.yaml

When setting storage type to Elasticsearch, the Cassandra env variable is generated while unneeded (+ the other way around). 
```
Environment:
STORAGE:                   elasticsearch
ES_SERVER_URLS:            https://elasticsearch.<hidden>:9200
ES_USERNAME:               elastic
ES_PASSWORD:               <set to the key 'password' in secret 'jaeger-elasticsearch'>  Optional: false
CASSANDRA_CONTACT_POINTS:  cassandra:9042
ES_NODES:                  https://elasticsearch.<hidden>:9200
ES_NODES_WAN_ONLY:         true
```
This PR fixes that.

Cleanup spark-cronjob storage env vars

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/templates/query-svc.yaml
charts/jaeger/values.yaml

Adding a proxy sidecar (i.e. oauth2-proxy) to the query pod to enable TLS & authentication capabilities.
The idea originated by the following blogpost: https://medium.com/jaegertracing/protecting-jaeger-ui-with-an-oauth-sidecar-proxy-34205cca4bb1
It is up to the user to use any sidecar of their choice, with the necessary volumes mounting (configuration file/certs/key).
Example configuration when using the the [OAuth2-proxy](https://oauth2-proxy.github.io/oauth2-proxy/). 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: jaeger-oauth-proxy-config
data:
oauth2-proxy.cfg: |
provider = "oidc"
https_address = ":4180"
upstreams = ["http://localhost:16686"]
redirect_url = "https://jaeger-svc-domain/oauth2/callback"
client_id = "jaeger-query"
client_secret = "xxxxxxxx"
oidc_issuer_url = …
```

[jaeger] Adding proxy sidecar to the jaeger-query pod 

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/agent-sa.yaml
charts/jaeger/templates/cassandra-schema-sa.yaml
charts/jaeger/templates/collector-sa.yaml
charts/jaeger/templates/es-index-cleaner-sa.yaml
charts/jaeger/templates/es-lookback-sa.yaml
charts/jaeger/templates/es-rollover-sa.yaml
charts/jaeger/templates/hotrod-sa.yaml
charts/jaeger/templates/ingester-sa.yaml
charts/jaeger/templates/query-sa.yaml
charts/jaeger/templates/spark-sa.yaml
charts/jaeger/values.yaml

Allows one to set `automountServiceAccountToken` on the serviceAccounts created by the upstream chart.
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server
N/A

[Jaeger] Add "automountServiceAccountToken" field to the serviceAccount Templates

---

charts/jaeger/Chart.yaml

It updates Kafka helm chart version from 11.x.x to 12.x.x. Its a major version upgrade but i looked at their changes, and most importantly they updated their charts api version to be v2 (compatible with helm3).
This is needed to we can use this change i made to the Kafka chart: https://github.com/bitnami/charts/pull/5988 and zookeeper chart:https://github.com/bitnami/charts/pull/5996
N.A

[jaeger] Update Kafka helm chart version to use automountServiceAccountToken feature

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/templates/service.yaml
charts/jaeger-operator/values.yaml

Signed-off-by: GitHub <noreply@github.com>
Adds support for NodePort in the Jaeger Operator
- fixes # https://github.com/jaegertracing/helm-charts/issues/229

[jaeger-operator] Adding support for NodePort in Jaeger Operator Helm Chart

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/cassandra-schema-job.yaml
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/ingester-deploy.yaml
charts/jaeger/templates/query-deploy.yaml

Signed-off-by: Smit Shah <shahsmit25193@gmail.com>
Add volume block if Cassandra's TLS flag is enabled.
- fixes #15

[jaeger] fixing cassandra tls volume

---

charts/jaeger/templates/es-rollover-hook.yml

Add 2 spaces in `podAnnotation`

[Jaeger] Fix Indent in podAnnotations es-rollover-hook

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/templates/query-svc.yaml
charts/jaeger/values.yaml

The PR adds the option to use a custom auth proxy with jaeger query by adding values to add additional `sidecars` to the jeager query pods and a value to customize the `targetPort` of the service. I also added another value to add `extraVolumes` which allows for more flexibility when configuring `sidecars`. Also even though the main use case for `sidecars` is probably to add a auth proxy it is not explicitly limited to that.

[jaeger]: Add option to use custom auth proxy with jaeger query 

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/values.yaml

Signed-off-by: Chad Wilson <chadw@thoughtworks.com>
Bumps the default operator version in the chart to `1.22.1` to resolve https://github.com/jaegertracing/jaeger-operator/issues/1426 for those using the operator Helm chart (without having to override the image tag)
Bumped the Chart version to `2.22.0` since this will actually indirectly trigger upgrades to Jaeger `1.22.0` (from `1.21.0`).

[jaeger-operator] update version of operator within the chart to v1.22.1

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/templates/deployment.yaml
charts/jaeger-operator/values.yaml

Specify custom log level for the operator.
- fixes #165

jaeger-operator - custom-log-level #165

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/templates/deployment.yaml
charts/jaeger-operator/values.yaml

Signed-off-by: Matteo Maponi <matteo.maponi@gmail.com>
Adds the ability to set a priority class name for the jaeger-operator chart. 
- fixes https://github.com/jaegertracing/helm-charts/issues/255

[jaeger-operator] Priority class name management

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/templates/_helpers.tpl

This PR adds a missing label from the `_helpers.tpl` template file that causes the `jaeger-operator-metrics` `service` to not pickup the `jaeger-operator` `pod`.
Fixes #247

[jaeger-operator] fix missing app.kubernetes.io/instance label

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/values.yaml

This PR allows the passing of environment variables to the oauth2-proxy sidecar for Jaeger.
The environment variables are passed in values.yaml under the `extraEnv` key, and are then passed into the oauth2-sidecar container.
The reasoning for this is so that we can use kubernetes secrets as environment variables within the oauth proxy ConfigMap.
Example:
```
extraEnv:
- name: test-env
valueFrom:
secretKeyRef:
name: test-secret
key: test-key
```
```
oAuthSidecar:
enabled: true
image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.0
args:
- --config
- /etc/oauth2-proxy/oauth2-proxy.cfg
- --client-secret
- "$(test-env)"
```
N/A

[jaeger] add environment variables to jaeger oauth sidecar

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/oauth-sidecar-configmap.yaml
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/values.yaml

This PR adds an optional configmap to be deployed with the oauth2-proxy-sidecar. 
In values.yaml, if the `config` key in the `oAuthSidecar` yaml is added, then the `oauth-sidecar-configmap.yaml` is deployed with the specified data. If the `config` key is not passed, then the `oauth-sidecar-configmap` will not be deployed.
If the config is passed, it is then automatically added as a volume and mounted as `jaeger-oauth-configuration`under the path `/etc/oauth2-proxy`
example values.yaml:
```
oAuthSidecar:
enabled: true
image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.0
pullPolicy: IfNotPresent
containerPort: 4180
args:
- --config
- /etc/oauth2-proxy/oauth2-proxy.cfg
extraEnv: []
extraConfigmapMounts: []
extraSecretMounts: []
config: |-
provider = "oidc"
https_address = ":4180"
upstreams = …
```

[jaeger] Add a configmap for the jaeger oauth sidecar

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/templates/role.yaml

Cluster role template wasn't reflecting the same level of permissions as upstream jaeger-operator. This PR makes helm chart follow upstream.
The issue is discussed here: https://github.com/jaegertracing/helm-charts/issues/250

[jaeger-operator] Synchronize cluster role template with jaeger operator

---

.github/workflows/lint-test.yaml

Updating kind-action version to see if it fixes the node not ready issues for lint test job.
- fixes #

[jaeger] Upgrade kind-action version

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-hpa.yaml
charts/jaeger/templates/ingester-hpa.yaml

Signed-off-by: sai kalyan <svytla@axon.com>
This PR fixes the HPA metrics list in a way that the order will be the same as how the HPA controller is saving it. There is a problem while using GitOps style of CD's like Argocd,harness...etc. The HPA controller is swaping the order of metrics section which is causing difference while using GitOps models CD's.
Example of HPA for Argocd:
HPA.yaml
```
spec:
scaleTargetRef:
apiVersion: apps/v1
kind: Deployment
name:  jaeger-collector
minReplicas: 2
maxReplicas: 10
metrics:
- type: Resource
resource:
name: cpu
targetAverageUtilization: 90
- type: Resource
resource:
name: memory
targetAverageUtilization: 90
```
Live Manifest that its applying:
```
name: jaeger-collector
namespace: jaeger-components
spec:
maxReplicas: 10
metrics:
- resource:
name: …
```

[jaeger] Reordering HPA metrics section

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/es-index-cleaner-cronjob.yaml
charts/jaeger/templates/es-lookback-cronjob.yaml
charts/jaeger/templates/es-rollover-cronjob.yaml
charts/jaeger/templates/es-rollover-hook.yml

Adds `activeDeadlineSeconds` value to all jobs to allow chart users to set a job deadlines which is currently required to terminate a job if sidecars are used.  This issue is also described [here](https://github.com/kubernetes/kubernetes/issues/25908) and there is not yet a proper solution for this.
An example use case would be if you are running elasticsearch in a service mesh which means in order for the job containers to send requests to elasticsearch it is required to also add them to the mesh hence injecting additional sidecars. The jobs will not finish by themselves since the sidecars are not shutting down which is a big issue for the hook/init job but also for all cronjobs because the pods are not cleaned up after the jobs finishes.

[jaeger]: Add activeDeadlineSeconds value to all jobs

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/values.yaml

Update version jaeger-operator to v1.24.0
- fixes #266

[jaeger-operator] Update version jaeger-operator to v1.24.0

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-ing.yaml
charts/jaeger/templates/hotrod-ing.yaml
charts/jaeger/templates/query-ing.yaml

Signed-off-by: bender316 <bender316@gmail.com>
Starting with kubernetes v1.22 the old api version "networking.k8s.io/v1beta1" for ingresses is no longer supported. This PR supports now both flavors.
- fixes #273

[jaeger] use networking.k8s.io/v1 for ingreses if available

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-ing.yaml
charts/jaeger/templates/hotrod-ing.yaml
charts/jaeger/templates/query-ing.yaml

Replace Ingress `v1`/`v1beta1` logic
Signed-off-by: Chris Werner Rau <cwrau@cwrcoding.com>
Uses bitnami's `common` chart to replace the Ingress `v1`/`v1beta1` logic, as that had a flaw
- fixes #277

[jaeger] Include bitnami's common chart to fix Ingress v1/v1beta1 distinction

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/templates/deployment.yaml
charts/jaeger-operator/values.yaml

Title explains itself but...
It enables custom labels for jaeger-operator deployment; We might need it for several reasons but in my case: to add a `cost-center` label in its pods.
n/a

[jaeger-operator] Enable extraLabels to deployment

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/templates/service-account.yaml
charts/jaeger-operator/templates/service.yaml
charts/jaeger-operator/values.yaml

Add annotations field on `service` and `serviceAccount` manifests.
It is really helpful to have it when we want to manage things through annotations on those resources, ie serviceAccount using IRSA (Iam roles for service account on AWS) and svc type load balancer.

[jaeger-operator] Add dynamic annotations to service and serviceAccount

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-ing.yaml
charts/jaeger/templates/hotrod-ing.yaml
charts/jaeger/templates/query-ing.yaml

Signed-off-by: Scharly Ochoa <sochoa@outlook.com.pe>
Currently pathType is added even when common.ingress.supportsPathType returns "false", this PR fixes the common.ingress.supportsPathType condition in all the ingress templates.
- fixes #

[jaeger] fixed common.ingress.supportsPathType condition

---

charts/jaeger/Chart.yaml

Upgrades Jaeger App version to 1.28.0
fixes #313

[jaeger] Upgrade Jaeger app version to latest - 1.28.0

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-ing.yaml
charts/jaeger/templates/hotrod-ing.yaml
charts/jaeger/templates/query-ing.yaml
charts/jaeger/values.yaml

Adds support for ingressClassName with keeping the old annotation option
- fixes #236 
- [V] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [V] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [V] Chart Version bumped
- [V] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)

[jaeger] add ingressClassName support

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/query-ing.yaml

Fix an issue introduced in v0.50.0 which causes no newline before the `rules` in `query-ing.yaml` when `query.ingress=true`.

[jaeger] Fix no newline before rules in query-ing.yaml

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-ing.yaml
charts/jaeger/templates/hotrod-ing.yaml

Fix an issue introduced in v0.50.0 which causes no newline before the `rules` in `collector-ing.yaml` & `hotrod-ing.yaml` when `query.ingress=true`.

[jaeger] Fix no newline before rules in collector-ing.yaml & hotrod-ing.yaml

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/values.yaml

Update jaeger-operator to 1.28.0. The changes to the operator are documented in it's [CHANGELOG](https://github.com/jaegertracing/jaeger-operator/blob/863caeb028c54dbd92c86ad54f4fce14abee9784/CHANGELOG.md#1280-2021-11-08).

[jaeger-operator] bump to version 1.28.0

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/ingester-deploy.yaml

[jaeger] Added missing affinity section for Ingester deployment

---

charts/jaeger/Chart.yaml
charts/jaeger/values.yaml

Signed-off-by: Manuel Bonk <gh@mbonk.de>
This PR sets the default image tag for `jaeger-es-index-cleaner` cronjob  from `latest` to  `jaeger.image.tag` (see https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/es-index-cleaner-cronjob.yaml#L48) In case you want to override the tag you can still do so manually, but I think it shouldn't be set by default to `latest`.

[jaeger] use jaeger.image.tag for es-index-cleaner tag

---

CONTRIBUTING.md

Signed-off-by: Manuel Bonk <gh@mbonk.de>
fixes typo in `contribution.md`

fix markdown typo

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/values.yaml

Signed-off-by: Login Victor <batazor111@gmail.com>
Bump jaeger-operator to v1.29.1

[jaeger-operator] bump jaeger-operator to v1.29.1

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/allinone-agent-svc.yaml
charts/jaeger/templates/allinone-collector-svc.yaml
charts/jaeger/templates/allinone-configmap.yaml
charts/jaeger/templates/allinone-deploy.yaml
charts/jaeger/templates/allinone-ing.yaml
charts/jaeger/templates/allinone-query-svc.yaml
charts/jaeger/templates/allinone-sa.yaml
charts/jaeger/values.yaml

This PR adds support for deploying the all-in-one container using the jaeger Helm chart. The all-in-one deployment deploys the following resources:
- Deployment for all-in-one container
- ServiceAccount for all-in-one container deployment
- ConfigMap for sampling config analogous to the sampling config ConfigMap used for jaeger-collector deployment
- Service for jaeger-agent
- Service for jaeger-collector
- Service for jaeger-query
- Ingress with jaeger-query as backend
- fixes #192

[jaeger] Add support for all-in-one deployment with in-memory storage

---

charts/jaeger/Chart.yaml

Signed-off-by: Greg Burton <9094087+gburton1@users.noreply.github.com>
Upgrades Kafka dependency to more recent version.
- fixes #332 
- [x ] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x ] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [x ] Chart Version bumped
- [x ] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)

[jaeger] Upgrade Kafka chart dependency from 12.x to 14.x

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/values.yaml

Update jaeger-operator to version v1.30.0
- fixes #

[jaeger-operator] Bump jaeger-operator to v1.30.0

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/_helpers.tpl
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/values.yaml

This PR adds support for being able to specify env variables for any grpc-plugin that's used. It also allows for specifying extra env for the collector just like the agent and query deployments allows.
I'm using the [jaeger-mongodb][1] with this updated chart as follows
```
storage:
type: grpc-plugin
grpcPlugin:
extraEnv:
- name: MONGO_URL
valueFrom:
secretKeyRef:
key: MONGO_URL
name: jaeger-secrets
```
which will render...
```
...
env:
- name: SPAN_STORAGE_TYPE
value: grpc-plugin
- name: MONGO_URL
valueFrom:
secretKeyRef:
key: MONGO_URL
name: jaeger-secrets
...
```
[1]:https://github.com/mongodb-labs/jaeger-mongodb
- fixes #

[jaeger] support grpcPlugin environment variables

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md

Bump jaeger-operator to [1.31.0](https://github.com/jaegertracing/jaeger-operator/releases/tag/v1.31.0):
* Fix panic caused by an invalid type assertion ([#1738](https://github.com/jaegertracing/jaeger-operator/pull/1738), [@frzifus](https://github.com/frzifus))
* Add ES autoprovisioning CR metric ([#1728](https://github.com/jaegertracing/jaeger-operator/pull/1728), [@rubenvp8510](https://github.com/rubenvp8510))
* Use Elasticsearch provisioning from OpenShift Elasticsearch operator ([#1708](https://github.com/jaegertracing/jaeger-operator/pull/1708), [@pavolloffay](https://github.com/pavolloffay))
Signed-off-by: Lucas Bickel (Adfinis) <lucas.bickel@adfinis.com>

[jaeger-operator] feat: bump jaeger-operator to 1.31.0

---

.github/PULL_REQUEST_TEMPLATE.md

Add a task to remind folks to update README.md so i don't forget like i did in #342

chore: add task asking to update README.md

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/values.yaml

jaeger-operator update to 1.32

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/es-index-cleaner-cronjob.yaml
charts/jaeger/templates/es-lookback-cronjob.yaml
charts/jaeger/templates/es-rollover-cronjob.yaml
charts/jaeger/templates/spark-cronjob.yaml

Changes apiVersion to correct value for cronjob resource based on k8s version.
- fixes #356

[jaeger] Add correct apiVersion for CronJob resource based on K8s version

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/allinone-ing.yaml
charts/jaeger/values.yaml

Add `allInOne.ingress.enabled` property to values to be able to disable and override parent ingress.
The default allInOne ingress use `defaultBackend` which leads to using `*` for the Ingress host which is not really convenient for usage.

[jaeger] Disable Jaeger allInOne ingress

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/allinone-deploy.yaml
charts/jaeger/values.yaml

Signed-off-by: guycarmy <guycarmy@gmail.com>
Allow specifying resources for all in one deployment.

[jaeger] Allow resources adjustment for allinone deployment

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/allinone-deploy.yaml
charts/jaeger/values.yaml

Signed-off-by: Ueslei Lima <uesleisantoslima@gmail.com>
We have now more flexibility to include extra configuration via environment variables to the allInOne deployment.

[jaeger] Including optional extraEnv in allInOne

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/agent-servicemonitor.yaml
charts/jaeger/templates/collector-servicemonitor.yaml
charts/jaeger/templates/ingester-servicemonitor.yaml
charts/jaeger/templates/query-servicemonitor.yaml
charts/jaeger/values.yaml

Adds support for passing in relabeling and metricRelabelings from the chart values for the servicemonitors objects.
- fixes #365

[jaeger] Add relabelings and metricRelabelings to serviceMonitors

---

charts/jaeger/Chart.yaml

Signed-off-by: czomo <tomaszjdul@gmail.com>
Set the backup of bitnami index after it has been clean up. See https://github.com/bitnami/charts/issues/10539 for more details
It is impossible to build dependencies after bitnami clean up the index.
Steps to reproduce:
- Clone repo 
- Go to jaeger directory
- Execute `helm dependency build`
Result:
```Downloading common from repo https://charts.bitnami.com/bitnami
Save error occurred:  could not find : chart common not found in https://charts.bitnami.com/bitnami
```

[jaeger] Patch bitnami repository index

---

.github/workflows/lint-test.yaml
charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/crd/crd.yaml
charts/jaeger-operator/templates/certificate.yaml
charts/jaeger-operator/templates/deployment.yaml
charts/jaeger-operator/templates/issuer.yaml
charts/jaeger-operator/templates/mutating-webhook.yaml
charts/jaeger-operator/templates/role.yaml
charts/jaeger-operator/templates/service.yaml
charts/jaeger-operator/templates/validating-webhook.yaml
charts/jaeger-operator/values.yaml

Signed-off-by: czomo <tomaszjdul@gmail.com>
Adding cert, weebhooks to adapt chart to jaeger-operator v.1.32+
- fixes #jaegertracing/helm-charts/issues/351

[jaeger-operator] Add cert machinery

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/values.yaml

Signed-off-by: czomo <tomaszjdul@gmail.com>
Updates jaeger-operator update to 1.34.1
- fixes https://github.com/jaegertracing/jaeger-operator/pull/1850

[jaeger-operator] update to 1.34.1

---

charts/jaeger-operator/COMPATIBILITY.md
charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/templates/NOTES.txt

Signed-off-by: czomo <tomaszjdul@gmail.com>
Add compatibility matrix, better marking corrupted charts  
- fixes #https://github.com/jaegertracing/helm-charts/pull/138

[jaeger-operator] Add compatibility matrix

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/crds/crd.yaml
charts/jaeger-operator/templates/crds.yaml
charts/jaeger-operator/templates/validating-webhook.yaml
charts/jaeger-operator/values.yaml

Signed-off-by: Micah Nagel <micah.nagel@parsons.com>
https://github.com/jaegertracing/helm-charts/pull/368 moved the CRD out of the special `chart/crds` helm chart folder and into `chart/crd`. While this did result in the chart making use of the already existing `chart/templates/crd.yaml` template to install the CRD, the other result is that you must install the helm chart without `jaeger.create` set to true, then upgrade after the CRD has been installed. If we make use of the `chart/crds` folder as recommended by the first method [here](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you) then the CRDs are installed before Helm applies the other manifests.
This unknowingly introduced what I would consider a breaking change into the chart …

[jaeger-operator] Refactor CRD to allow Jaeger CR creation on initial install

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-ing.yaml
charts/jaeger/templates/query-ing.yaml
charts/jaeger/values.yaml

Signed-off-by: Nicolas <nicorabatel@gmail.com>
Adding values to be able to add custom labels in query and collector ingresses
- fixes  https://github.com/jaegertracing/helm-charts/issues/104
~- [ ] README.md has been updated to match version/contain new values~

[jaeger] Custom labels in query and collector ingresses

---

charts/jaeger-operator/COMPATIBILITY.md
charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/crds/crd.yaml
charts/jaeger-operator/templates/service.yaml
charts/jaeger-operator/values.yaml

Updates to Jaeger Operator 1.35.0: Update chart version, appversion, image tag, CRD, compatibility table.

[jaeger-operator] Update to Jaeger Operator 1.35.0

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/collector-svc.yaml
charts/jaeger/values.yaml

Signed-off-by: Tiago Angelo <kurtis.angelo@gmail.com>
Adds the ability to enable Collector to receive trace data via OTLP also allows changing the default ports.
- fixes #382

[jaeger] Enable the OTLP receiver

---

charts/jaeger/Chart.yaml

Minor Jaeger version upgrade. It pulls in a [significant bug fix](https://github.com/jaegertracing/jaeger/pull/3819) that is causing crashes in production for many people.
- [x ] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x ] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [x ] Chart Version bumped
- [x ] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)

Upgrade Jaeger appVersion for the chart

---

charts/jaeger-operator/COMPATIBILITY.md
charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/crds/crd.yaml
charts/jaeger-operator/values.yaml

Updates operator chart to latest version (1.36.0). Also syncs the CRD with the latest (1.36.0) release manifests.

[jaeger-operator] Update operator chart to 1.36.0

---

charts/jaeger/Chart.yaml

Signed-off-by: Loc Mai <locmai0201@gmail.com>
Upgrade Kafka chart to ^18.0.8 which contains the next major version of Kafka from 2.8 to 3.2.0
- fixes  #352
I was able to upgrade the Kafka without causing any side effect for Jaeger. And the tracing spans could flow in normally after the upgrade.
Take the guidance from Kafka into account, we could also update the document to set the server.properties right, note that I didn't take these steps, a simple version bump solve the case.
1. Add an upgrading section for major version from Kafka
2. Add the `inter.broker.protocol.version=<current-version-to-upgrade-from>` (latest: inter.broker.protocol.version=2.8.1) into the Kafka config section.
3. Apply the change
4. After rolling out all of the Kafka pods, remove the …

[jaeger] chore: bumping Kafka chart version to ^18.0.8

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/es-index-cleaner-cronjob.yaml
charts/jaeger/templates/es-lookback-cronjob.yaml
charts/jaeger/templates/es-rollover-cronjob.yaml
charts/jaeger/templates/spark-cronjob.yaml
charts/jaeger/values.yaml

Add ttlSecondsAfterFinished entry to esIndexCleaner for removing completed jobs of the ElasticSearch Index Cleaner after the configured amount of time
Make ttlSecondsAfterFinished for esIndexCleaner configurable
- fixes #393

[jaeger] Add ttlSecondsAfterFinished entry to esIndexCleaner job

---

charts/jaeger-operator/COMPATIBILITY.md
charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/values.yaml

Updates the chart to use the latest operator version (1.37.0). Validated no other changes (to CRD, etc) required.

[jaeger-operator] Update Jaeger Operator Chart to 1.37.0

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/allinone-collector-svc.yaml
charts/jaeger/templates/allinone-deploy.yaml
charts/jaeger/values.yaml

Enables the native support for OpenTelemetry in Jaeger All-in-one

[jaeger] OpenTelemetry Protocol (OTLP) enabled on Jaeger All-in-one

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/query-deploy.yaml

Signed-off-by: Tiago Angelo <kurtis.angelo@gmail.com>
It fixes a wrong indent that made it impossible to configure custom sidecars
- fixes #402

[jaeger] Fix sidecar indentation

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/allinone-deploy.yaml
charts/jaeger/values.yaml

We have added the NodeSelector for the All in One Image and would like this feature to be integrated into the Jaegertracing Helm Charts.
Previously, there was no NodeSelector for the AllinOne Deployment so there was no way of deploying the AllinOne Deployment across multiple NodeGroups into a selected Nodegroup. This PR fixes this by adding the NodeSelector into the AllinOne Template and allows the Roll out of the AllinOne Deployment into a specific Nodegroup.
Signed-off-by: Ramazan Kara [ramazan.kara@otto.de](mailto:ramazan.kara@otto.de)
Co-authored-by: Otto Wagner [otto.wagner@otto.de](mailto:otto.wagner@otto.de)

[Jaeger] - Feature - Added NodeSelector for All in One Image.

---

charts/jaeger-operator/COMPATIBILITY.md
charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/crds/crd.yaml
charts/jaeger-operator/values.yaml

Signed-off-by: Tunde Oladipupo <simplytunde@gmail.com>
Fixes https://github.com/jaegertracing/helm-charts/issues/410

[jaeger-operator] Update Jaeger Operator to 1.39.0

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-svc.yaml
charts/jaeger/values.yaml

Hi. 
gRPC client balancing requires headless services in order to work. More info here - <https://kubernetes.io/blog/2018/11/07/grpc-load-balancing-on-kubernetes-without-tears/>
This change allows to set collector service type to headless. We use it in production without problems.

[jaeger] Have an ability to make collector svc headless

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/allinone-deploy.yaml
charts/jaeger/templates/allinone-ing.yaml
charts/jaeger/values.yaml

Signed-off-by: Petrus.Z <silencly07@gmail.com>
Add `values.allInOne.podLabels`property to values, and complete the allInOne ingress, thus disable ingress by default.

[jaeger] Add podLabels and complete ingress

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/allinone-deploy.yaml

Signed-off-by: palmheads <daz@planetnz.com>
When using the all-in-one jaeger deploy with helm, opens up port 16685 which currently gets a connection refused
- fixes #3852

[jaeger] bumping chart & opening up 16685 port

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/allinone-deploy.yaml
charts/jaeger/values.yaml

Signed-off-by: Pierre Tessier <pierre@pierretessier.com>
Adds the ability to specify args for the All in one mode.
This helps unblock [Issue #515 with the OpenTelemetry Demo Helm chart](https://github.com/open-telemetry/opentelemetry-helm-charts/issues/515)

[jaeger] - add args to allinone

---

charts/jaeger/Chart.yaml

Signed-off-by: Greg Burton <9094087+gburton1@users.noreply.github.com>
The jump from from 18.x to 19.x Kafka chart is pretty minor. The underlying Kafka version jumps from 3.2 to 3.3.
- fixes #
- [x ] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ x] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [ x] Chart Version bumped
- [x ] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)
- [ x] README.md has been updated to match version/contain new values

jaeger: upgrade Kafka chart dependency from 18.x to 19.x

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/_helpers.tpl
charts/jaeger/templates/agent-ds.yaml
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/es-index-cleaner-cronjob.yaml
charts/jaeger/templates/es-lookback-cronjob.yaml
charts/jaeger/templates/es-rollover-cronjob.yaml
charts/jaeger/templates/es-rollover-hook.yml
charts/jaeger/templates/ingester-deploy.yaml
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/templates/spark-cronjob.yaml

[jaeger] fixes #329 missing prefix on esCronJobs

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/templates/deployment.yaml
charts/jaeger-operator/templates/service.yaml
charts/jaeger-operator/values.yaml

Changes in this PR allow for modifying default webhook and metrics ports.
This is directly related to below two PR's
- [jaeger-operator](https://github.com/jaegertracing/jaeger-operator/pull/1991)
- [documentation](https://github.com/jaegertracing/documentation/pull/582)
- fixes #

[jaeger-operator] will allow to change webhook and metrics ports

---

charts/jaeger/Chart.yaml
charts/jaeger/values.yaml

- fixes query.ingress for nginx-ingress-controller (probably more ingress controllers)
- used in here https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/query-ing.yaml#L4 and here https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/query-ing.yaml#L28 but not defined :)
- if it's not defined, chart will produce paths like this:
```yaml
- pathType: ImplementationSpecific
backend:
service:
name: jaeger-query
port:
number: 80
```
- missing the `path: /`, I'm not sure if it's problem only for `nginx-ingress-controller` or for more controllers

[jaeger] fix (query,collector) basePath

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/es-index-cleaner-cronjob.yaml

This PR removes the cmdline arguments of the storage from the es-index-cleaner arguments
- fixes #424

[jaeger] Remove storage.cmdArgs from es index cleaner commandline args

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/allinone-deploy.yaml

Signed-off-by: Pierre Tessier <pierre@pierretessier.com>
Uses the Helm [tpl](https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function) function to allow for command line args to be templated. This is required when Jaeger is used as a chart dependency and some options can only be determined at helm templating time (ie: release name).
This allows for the OpenTelemetry demo to leverage Jaeger for tracing with Prometheus-backed metrics store configured in the Jaeger AllInOne deploy as merged recently in the otel demo [PR 655](https://github.com/open-telemetry/opentelemetry-demo/pull/655) 
The OpenTelemetry demo helm chart will have a section to configure the prometheus sever url that looks like this:
```yaml
allInOne:
enabled: true
args:
- "--prometheus.server-url"
- …
```

[jaeger] - allinone use tpl function for args

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/templates/service.yaml
charts/jaeger-operator/values.yaml

This PR adds a value called 'serviceExtraLabels' to make it possible to add a label to the service you may not want to have in the operator to for example create a 'serviceMonitor' for it.
- fixes #

[jaeger-operator] Adding serviceExtraLable for service

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/_helpers.tpl
charts/jaeger/values.yaml

Signed-off-by: Piotr Klubinski <pklubinski@gmail.com>
This PR allows to not render ES_USERNAME or ES_PASSWORD if `storage.elasticsearch.anonymous: true`.
- fixes #441

[jaeger] Will allow anonymous login to ElasticSearch

---

charts/jaeger/Chart.yaml
charts/jaeger/values.yaml

Most images are set to a pullPolicy of IfNotPresent, but the following images were set to Always prior to this commit:
- spark
- esIndexCleaner
- esRollover
- esLookback
- hotrod
This makes it confusing when testing local images in a minikube cluster. Instead be consistent and use IfNotPresent for all images, which makes local testing easier.
Signed-off-by: Jesse Hathaway <jhathaway@wikimedia.org>

[jaeger] Make pullPolicy consistently IfNotPresent

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/templates/certificate.yaml
charts/jaeger-operator/values.yaml

Allow setting the `Certificate` `Issuer` kind to `ClusterIssuer` while retaining the default type of `Issuer`.
If `certs.issuer.create=true` is set, the Certificate's Issuer Kind will always be `Issuer`, since this change does not allow the built-in issuer's kind to be modified.
- fixes #386

[jaeger-operator] Allow setting the Certificate Issuer Kind

---

charts/jaeger/Chart.yaml

Prior to this commit helm could determine, prior to an apply, whether the chart is compatible with the local Kubernetes cluster.
After this commit helm is able to reject the apply immediately.

[jaeger] Add kubeVersion to indicate Kubernetes compatibility

---

charts/jaeger/Chart.yaml

Some Kubernetes vendors use a pre-release format for versioning, AWS EKS example: v1.24.8-eks-ffeb93d
Current requirements are strict only with a release version 
as result >= 1.21 don't tolerate with v1.24.8-eks-ffeb93d
Allow pre-release format with appendix -0 in the requirements for the chart.
[more info about working with pre-release format](https://github.com/Masterminds/semver#working-with-prerelease-versions)

[jaeger] Allow pre-release format in helm-chart requirements

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/values.yaml

Support InitContainers in collector deployment
- fixes #452

[jaeger] #452 support initContainers

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/cassandra-schema-job.yaml
charts/jaeger/values.yaml

By default, the behavior will be identical to what it was before.  Enabled by default.
This flag though, when set to false will disable the creation of the cassandra-schema-job Job resource.
I have a use case where I don't want the helm chart to attempt to run the cassandra-schema-job at all.  Schema creation is our cassandra db is handled another way.  Also I think I'm having trouble with this job running cleanly against our ScyllaDB / cassandra environment.  So in the interest of having cleaner k8s deployments, wanted to just have the option to be able to turn this off.
This PR adds a flag in values. `storage.cassandra.schemaJobEnabled` which defaults to `true` so that existing behavior doesn't change at all.   If you change the value of `storage.cassandra.schemaJobEnabled=false` Then …

[jaeger] Add flag enabling the ability to disable the cassandra-schema Job

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/allinone-ing.yaml
charts/jaeger/templates/collector-ing.yaml
charts/jaeger/templates/hotrod-ing.yaml
charts/jaeger/templates/query-ing.yaml
charts/jaeger/values.yaml

It adds the option for the user to specify the ingress `pathType` because the current implementation is very inflexible.
- fixes #423
- fixes #435

[jaeger] feat: specify ingress pathType as variable ✨

---

charts/jaeger-operator/COMPATIBILITY.md
charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/values.yaml

Updates jaeger operator values to 1.42.0 & updated chart value

[jaeger-operator] Update Jaeger Operator to 1.42.0

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/_helpers.tpl
charts/jaeger/templates/collector-networkpolicy-egress.yaml
charts/jaeger/templates/collector-networkpolicy-ingress.yaml
charts/jaeger/templates/query-networkpolicy-egress.yaml
charts/jaeger/templates/query-networkpolicy-ingress.yaml
charts/jaeger/values.yaml

Adds network policy support to the query and collector components.

[jaeger] Network policy support, query & collector

---

charts/jaeger-operator/COMPATIBILITY.md
charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/values.yaml

Update Jaeger operator image version to latest upstream release 1.43.0
Update Jaeger operator Helm chart version to 2.42.0

jaeger-operator update image to latest 1.43.0 and bump chart version

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/templates/deployment.yaml
charts/jaeger-operator/values.yaml

Allows configuring the security context for jaeger operator container. This enables configuration of options such as `capabilities`, `allowPriviledgeEscalation`, etc which are required in many platforms, orgs and while using the new restricted Pod security admission mode.
- fixes #

[jaeger-operator] feat: allow configuring container security context for jaeger operator

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/hotrod-deploy.yaml
charts/jaeger/values.yaml

* Default the `args` in the container to "all". This is the current default in the container.
* Allow extra arguments to be added to the `hotrod` container
* Allow environment variables to be added to the `hotrod` container
- fixes #462

[jaeger] add extraArgs and extraEnv to hotrod

---

charts/jaeger-operator/COMPATIBILITY.md
charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/values.yaml
charts/jaeger/Chart.yaml

Signed-off-by: Chris O'Connell coconnell@bridgephase.com
***Chart/Image Upgrade****
Bump jaeger operator image and helm chart versions.

jaeger-operator chart update

---

charts/jaeger/Chart.yaml

Upgrades Jaeger tenant Helm chart version and AppVersion which is used by the values file for default image.

[jaeger] tenant app/chart version upgrade to match operator

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/ingester-deploy.yaml

Until now it was not possible to configure brokers, topic and authentication via environment variables because there where always environment variables added that sourced the values from the `values.yaml` file.
When the configuration values are only available through ConfigMaps this is not possible to provide via `values.yaml`.

[jaeger] Add option to configure ingester only via environment variables

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/values.yaml

Version 0.71.5 added configurable otlp port names to the collector service, but introduced some typos, which break otlp for http & gRPC. I'm not sure why they would be configurable, so I haven't also made the port names on the actual deployment configurable to match the service, but at least this should fix connectivity
Signed-off-by: Jon Bates <jonathan.bates@team.bumble.com>
Fixes regression in 0.71.5
Can't see one that has been raised

[jaeger] Fix otlp service regression in 0.71.5

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/agent-ds.yaml
charts/jaeger/templates/allinone-deploy.yaml
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/ingester-deploy.yaml
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/values.yaml

This PR adds an option of giving "envFrom" to the deployment manifest.
Taking changes from original PR: https://github.com/jaegertracing/helm-charts/pull/387
(which was in a weird state with multiple commits and dco check failing)

[jaeger] add option to add "envFrom" in deployments

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-hpa.yaml
charts/jaeger/templates/ingester-hpa.yaml

Configured the collector and ingester HPA resources to additionally only deploy if components themselves are enabled.

[jaeger] Configure collector and ingester HPAs to only deploy if component is enabled

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/templates/deployment.yaml

This PR sets the `--metrics-port` & `--webhook-bind-port` so if these values are changed from the default the operator continues to work correctly.
- Fixes #473

[jaeger-operator]: Fixed support for custom ports

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/allinone-deploy.yaml
charts/jaeger/values.yaml

This PR adds the ability to mount secrets to the all-in-one deployment through the `.Values.allInOne.extraSecretMounts` value. Implementation follows the implementation in [collector-deploy.yaml](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/collector-deploy.yaml).
- fixes #484

[jaeger] extraSecretMounts for all-in-one configuration

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/values.yaml

This sets the default values of the `collector.service.otlp.grpc` and `collector.service.otlp.http` to `{}` and also fixes a bug with the deploy logic that would prevent overriding these values with `null`. At the very least, the deploy change is needed because the values cannot be overridden with `null` and helm does not allow overriding them with `{}` (see https://github.com/helm/helm/issues/5407).

[jaeger] Unset default collector OTLP ports

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/allinone-deploy.yaml
charts/jaeger/values.yaml

Adds a Helm value for `allInOne.replicas`.
- fixes #493

[jaeger] make replicas a Helm value instead of hardcoding it

---

charts/jaeger/Chart.yaml

Reverting Kafka chart version as new version is not working as expected and having issues with ingester/collector pods coming online due to Kafka SSL handshake issues. New kafka chart had major design changes migrating from Zookeeper to KRaft mode.
```
Ingester/Collector pod logs
"error":"kafka: client has run out of available brokers to talk to: EOF"
```
reverting kafka to old chart which is working, reverting this [PR](https://github.com/jaegertracing/helm-charts/pull/498/files) which was merged
- fixes #

[jaeger] Revert - Bumping kafka chart dependency from 19.x to 24.x

---

charts/jaeger-operator/COMPATIBILITY.md
charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/values.yaml

Bump jaeger operator image and helm chart versions to `1.47.0`
N/A

[jaeger-operator] Bump jaeger-operator and helm chart

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/values.yaml

[jaeger] Add resources to oAuthSidecar to allow setting in case of quota requirements
It updates the `charts/jaeger/templates/query-deploy.yaml` to add the ability to set resources via a values.yaml.
Could not deploy with Oauth2 proxy sidecar in an environment that enforces quotas without manual config modifications.
- fixes #

[jaeger] Add resources to oAuthSidecar

---

charts/jaeger-operator/README.md

Configuration table display is broken in jaeger-operator README.md. This PR fixes the markdown table formatting.
- [ V] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ V] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [ V] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)

[jaeger-operator] fix config table in jaeger-operator README.md

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/allinone-deploy.yaml
charts/jaeger/values.yaml

For a project I require using a different repo for the all-in-one image, requiring pull secrets. This PR adds the ability to set these in the chart values.
-

[jaeger] Added imagePullSecrets option for all-in-one deployment.

---

charts/jaeger-operator/COMPATIBILITY.md
charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/values.yaml

Bump jaeger operator image and helm chart versions to 1.49.0
N/A
- [ x] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ x] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [ x] Chart Version bumped
- [ x] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)
- [ x] README.md has been updated to match version/contain new values

[jaeger-operator] Update helm chart to version 1.49.0

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/_helpers.tpl
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/es-index-cleaner-cronjob.yaml
charts/jaeger/templates/es-lookback-cronjob.yaml
charts/jaeger/templates/es-rollover-cronjob.yaml
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/values.yaml

Adds the possibility to mount a secret with TLS certificates & keys that contains more than one value. The standard secret mounted always expects the `ca-cert.pem` key to be present, which makes activating TLS complicated in non-default scenarios. 
- Fixes #513 
- Possibly related to #443

[jaeger] more flexible TLS variables

---

charts/jaeger/Chart.lock
charts/jaeger/Chart.yaml

Updates Jaeger to the latest version.
Also adds a Chart.lock file to ensure local development can work as intended with Helm [dependency build](https://helm.sh/docs/helm/helm_dependency_build/)

[jaeger] Update jaeger version to latest

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/es-rollover-hook.yml

This PR corrects the situation when the parameters `.Value.storage.elasticsearch.tls` did not work for `es-rollover-hook.yml`
Added a section for mounting a tls secret from elasticsearch parameters.
- fixes https://github.com/jaegertracing/helm-charts/issues/521

[jaeger] fix .Values.storage.elasticsearch.tls for es-rollover-hook

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/allinone-sa.yaml
charts/jaeger/templates/es-index-cleaner-sa.yaml
charts/jaeger/templates/es-lookback-sa.yaml
charts/jaeger/templates/hotrod-sa.yaml
charts/jaeger/templates/ingester-sa.yaml
charts/jaeger/templates/spark-sa.yaml
charts/jaeger/values.yaml

Annotations for ServiceAccounts can now be specified with helm values
- fixes #518 
- [ * ] [DCO](https://github.com/jaegertracing/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ * ] Commits are [GPG signed](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification)
- [ * ] Chart Version bumped
- [ * ] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)
- [ * ] README.md has been updated to match version/contain new values

[jaeger] Allow Jaeger ServiceAccounts to have annotations specified

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/values.yaml

According to the chart appversion https://github.com/jaegertracing/helm-charts/blob/ce83c06bd256af413c53ce1110d38d96a31156c0/charts/jaeger-operator/Chart.yaml#L5
and readme
https://github.com/jaegertracing/helm-charts/blob/ce83c06bd256af413c53ce1110d38d96a31156c0/charts/jaeger-operator/README.md?plain=1#L62
it looks like the jaeger-operator image should be `1.52.0`, however it hasn't been updated in the values file.
- fixes #535

[jaeger-operator] Bump image in values to 1.52.0

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/ingester-deploy.yaml
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/values.yaml

Adds optional initContainers for jaeger query and ingester deployments
- fixes #512
~- [] README.md has been updated to match version/contain new values~

[jaeger] Adding optional initContainers for jaeger query and ingester deployments

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/query-deploy.yaml

Without this, changes to the oauth2-proxy configuration don't affect any metadata in the Deployment, meaning pods must be deleted manually after a configuration change.

[jaeger] make Deployment depend on oauth2 config, if enabled

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/templates/_helpers.tpl
charts/jaeger/templates/agent-ds.yaml
charts/jaeger/templates/allinone-deploy.yaml
charts/jaeger/templates/cassandra-schema-job.yaml
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/es-index-cleaner-cronjob.yaml
charts/jaeger/templates/es-lookback-cronjob.yaml
charts/jaeger/templates/es-rollover-cronjob.yaml
charts/jaeger/templates/es-rollover-hook.yml
charts/jaeger/templates/hotrod-deploy.yaml
charts/jaeger/templates/ingester-deploy.yaml
charts/jaeger/templates/query-deploy.yaml
charts/jaeger/templates/spark-cronjob.yaml
charts/jaeger/values.yaml

- Splits image registry, repository, and tag. Allowing for overriding of any one without affecting the other
- Allow overriding the image registry in the global config
- Allow setting the pullSecrets at the global level
- relates to  #182

[jaeger] Allow overriding image registry at the global level

---

charts/jaeger/Chart.yaml
charts/jaeger/README.md
charts/jaeger/values.yaml

[jaeger] Update oauth sidecard to 7.6.0

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/templates/deployment.yaml
charts/jaeger-operator/values.yaml

Allow configuring replica count for jaeger operator.
Enable leader election if the given number is greater than 1.
`N/A`

[jaeger-operator] Allow configuring replica count for jaeger operator

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/_helpers.tpl
charts/jaeger/templates/allinone-deploy.yaml
charts/jaeger/values.yaml

Adds badger support for the AllInOne deployment. By default it uses ephemeral badger, but a user-provided PVC can be used to use persistence features. 
Conflicts with #527 because of the securityContext
- fixes #511 
- fixes #390

[jaeger] Add badger support for AllInOne deployment

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/templates/deployment.yaml
charts/jaeger-operator/values.yaml

Allow configuring topology spread constraints for jaeger operator.
`N/A`

[jaeger-operator] Allow configuring topology spread constraints for jaeger operator

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/templates/deployment.yaml
charts/jaeger-operator/values.yaml

Allow configuring extra command line arguments for jaeger operator.
- fixes #232

[jaeger-operator] Allow configuring extra command line arguments for jaeger operator

---

.github/workflows/lint-test.yaml
charts/jaeger/Chart.lock
charts/jaeger/Chart.yaml
charts/jaeger/values.yaml

This PR changes the Elasticsearch helm chart to https://github.com/bitnami/charts/tree/main/bitnami/elasticsearch to migrate to a supported helm chart since the current one is deprecated. I bumped the major version since the helm chart is getting changed. 
I was able to get this to work with the default settings. Out of the box Elasticsearch doesn't have auth support unless `security.enabled` is set. 
To migrate existing workloads/data I was able to follow instructions on migrating the volumes to a new PVC thats created by the helm chart. This is similar to the Kafka migration that was done:
```
REPLICA=0
OLD_PVC="elasticsearch-master-elasticsearch-master-${REPLICA}"
NEW_PVC="data-elasticsearch-master-${REPLICA}"
PV_NAME=$(kubectl get pvc $OLD_PVC -o jsonpath="{.spec.volumeName}" -n …
```

[jaeger] Elasticsearch chart migration

---

charts/jaeger/Chart.yaml
charts/jaeger/artifacthub-repo.yml

Adds a file for us to identify this repo as the official chart. This will allow me to correct the listing as official and fix a security gap we have in the Jaeger CLOMonitor report. I added myself to the Chart and new artifacthub-repo.yml temporarily. 
I have also bumped the version of the chart.
https://github.com/jaegertracing/jaeger/issues/5363

Add artifacthub-repo file and jkowall to the list of maintainers

---

charts/jaeger/Chart.yaml
charts/jaeger/artifacthub-repo.yml

Commented out the RepositoryID for now until we get one after claiming ownership. 
https://github.com/jaegertracing/jaeger/issues/5363

[jaeger] Adding comment in artifacthub-repo to try to claim ownership

---

artifacthub-repo.yml

Adds the file to gh-pages branch
related to : https://github.com/jaegertracing/jaeger/issues/5363
- [NA] Chart Version bumped
- [NA] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)
- [NA] README.md has been updated to match version/contain new values

Adding artifacthub-repo.yml to gh pages

---

artifacthub-repo.yml

Adds the ID from Artifact Hub to the yaml file 
https://github.com/jaegertracing/jaeger/issues/5363
- [NA] Chart Version bumped
- [NA] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)
- [NA] README.md has been updated to match version/contain new values

Adding official Artifact Hub ID

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/_helpers.tpl

Fix typo preventing use of global.imageRegistry
Fix typo preventing use of global.imageRegistry
- fixes #

[jaeger] Fix typo preventing use of global.imageRegistry

---

charts/jaeger-operator/COMPATIBILITY.md
charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/values.yaml

Upgrades the jaeger-operator chart to use version `1.57`
N/A

[jaeger-operator] upgrade jaeger-operator to latest 1.57 version

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/allinone-deploy.yaml
charts/jaeger/templates/allinone-sa.yaml
charts/jaeger/values.yaml

- [jaeger] allInOne add option `automountServiceAccountToken` for serviceaccount
- [jaeger] allInOne add `affinity` support
- [jaeger] allInOne add `topologySpreadConstraints` support
- [jaeger] allInOne add `podSecurityContext` and `containerSecurityContext` support
- fixes #

[jaeger] add new options, improvements into allInOne

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/allinone-deploy.yaml
charts/jaeger/values.yaml

Add `tolerations` option to allInOne deployment

[jaeger] allInOne add option tolerations

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-svc.yaml
charts/jaeger/templates/query-svc.yaml
charts/jaeger/values.yaml

This PR adds the ability to edit the port name and target port name in the Jaeger query and collector services. This enhancement allows users to customize the port names, which is useful for enforcing HTTPS via Istio by renaming the port with the prefix http.
This PR fixes issue [#589](https://github.com/jaegertracing/helm-charts/issues/589).
- fixes #

[jaeger] Add ability to edit port name and target port name in query and collector services

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/templates/role.yaml

Add ingressclasses to role.yaml so that the CRD has correct permissions when rbac.cluster.Role is set
- fixes #581

[jaeger-operator] Add ingressclasses to role.yaml so that the CRD has correct permissions when rbac.cluster.Role is set

---

charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/templates/role.yaml

[Original fix](https://github.com/jaegertracing/helm-charts/pull/591) added ingressclasses to `extensions` instead of `networking.k8s.io`
- fixes https://github.com/jaegertracing/helm-charts/issues/581
- fixes https://github.com/jaegertracing/helm-charts/issues/593
Error in logs:
```
~ kubectl logs -n jaeger jaeger-operator-6867cc744c-6pq6z
W0731 09:34:51.891865       1 reflector.go:539] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: 
failed to list *v1.IngressClass: ingressclasses.networking.k8s.io is forbidden:
User "system:serviceaccount:jaeger:jaeger-operator" cannot list resource "ingressclasses" in API group "networking.k8s.io" at the cluster scope
E0731 09:34:51.891968       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: 
Failed …
```

[jaeger-operator] Add ingressclasses to correct apiGroup

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/spark-cronjob.yaml
charts/jaeger/values.yaml

Adding possibility to configure securityContext for spark CronJob
-

[jaeger] Add securityContext for spark cron job

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/cassandra-schema-job.yaml
charts/jaeger/values.yaml

* Adds cassandra schma job toleration
- fixes #547 which didn't have a GPG-signed commit

[jaeger] Add cassandra schema job toleration

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/query-deploy.yaml

The sidecar is missing the securityContext entry, and it makes it difficult to apply specific settings in the context of K8s PSS (migrating from PSP for example).

[jaeger] Add securityContext for the oauth sidecar in query-deploy.yaml

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/collector-svc.yaml

Adds missing loadbalancer ip to collector service
- fixes #136

[jaeger] Add missing loadBalancerIp to collector-svc template

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/_helpers.tpl
charts/jaeger/templates/allinone-deploy.yaml

Allow different storage backend type for allInOne than just memory/badger.
- fixes # https://github.com/jaegertracing/helm-charts/issues/602
- [] README.md has been updated to match version/contain new values

[Jaeger] Jaeger allInOne allow different storage types

---

charts/jaeger-operator/COMPATIBILITY.md
charts/jaeger-operator/Chart.yaml
charts/jaeger-operator/README.md
charts/jaeger-operator/values.yaml

- jaeger-operator upgrade to latest 1.61.0 from 1.57.0

jaeger-operator upgrade to latest 1.61.0

---

.github/actions/prepare-k8s/action.yaml
.github/workflows/lint-test.yaml

* Extracts common k8s setup steps into a reusable action
* Move install test into a separate job
The CI testing of the chart does not cover installing 3rd party storage backends. PR #614 adds an extra test but either has to do it sequentially within the single job or replicate a lot of setup for another job / workflow. With this refactoring #614 would be able to add a new job to the existing workflow with minimal amount of boiler plate.

Share setup sub-action in CI

---

.github/workflows/lint-test.yaml
charts/jaeger/Chart.yaml
charts/jaeger/templates/_helpers.tpl
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/query-deploy.yaml

- fixes #
1) the service name for the elastic search was not matching with jaeger-collector/query deployment 
2) added ci test for it

[jaeger] Fix hostname for Elasticsearch service and add CI test

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/_helpers.tpl
charts/jaeger/templates/collector-deploy.yaml
charts/jaeger/templates/query-deploy.yaml

This PR makes the curl image that is used for elasticsearch respect `global.imageRegistry`, such that:
```sh
helm template --set provisionDataStore.elasticsearch=true . | grep curlimages
image: curlimages/curl
image: curlimages/curl
```
```sh
helm template --set provisionDataStore.elasticsearch=true,global.imageRegistry=example.com . | grep curlimages
image: example.com/curlimages/curl
image: example.com/curlimages/curl
```

[jaeger] Make curl image respect global.imageRegistry

---

charts/jaeger/templates/_helpers.tpl

The keyword changed, so we have to carry the env vars with us in that case.
Allows gRPC storage to be used in newer jaeger-query releases when deployed with helm.
- fixes #

[jaeger] Support gRPC storage in Jaeger >=1.60.0

---

charts/jaeger/Chart.yaml
charts/jaeger/templates/cassandra-schema-job.yaml
charts/jaeger/values.yaml

Adds ability to specify `nodeSelector` for Schema Job
- fixes #325

[jaeger] Add nodeSelector to Schema

---

.github/actions/prepare-k8s/action.yaml
.github/workflows/lint-test.yaml

Replaces the actions/setup-python@v2 step configured with python-version: 3.7
Updates it to actions/setup-python@v4 with python-version: '3.11'
- fixes #

[ci] bump Python version from 3.7 to 3.11 in GitHub Actions"bump python version

---

.github/actions/prepare-k8s/action.yaml
.github/workflows/lint-test.yaml

Replaces the actions/setup-python@v2 step configured with python-version: 3.7
Updates it to actions/setup-python@v4 with python-version: '3.11'
- fixes #

[ci] bump Python version from 3.7 to 3.11 in Helm lint workflow

---

charts/jaeger/templates/allinone-deploy.yaml
charts/jaeger/templates/user-config.yaml

- So , We lacked the capability to mount ui-configs ( which are different from jaeger config.yaml )
- The functionality was provided for jaeger-query and other components but not allInOne 
- Added a configMap and mounting the ui-config to the deployment

[jaeger] Set UI-Config for jaeger allInOne deployment
