jaegertracing/helm-charts

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- charts/jaeger/Chart.yaml
- charts/jaeger/README.md
- charts/jaeger/values.yaml
- ct.yaml
See #1 for context.
This chart should initially fail CI, until I push another commit that bumps the version, then it should pass.
Signed-off-by: Scott Rigby <scott@r6by.com>
> Update Readme for jaeger chart

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
See https://github.com/helm/charts-repo-actions-demo
Fixes several issues
> Update Helm action versions for CI/CD

- charts/jaeger/Chart.yaml
- charts/jaeger/README.md
- charts/jaeger/templates/cassandra-schema-job.yaml
- charts/jaeger/templates/collector-deploy.yaml
- charts/jaeger/templates/query-deploy.yaml
- charts/jaeger/values.yaml
Here is the discussion thread where it was decided to add this functionality
https://github.com/jaegertracing/jaeger-operator/pull/837
> Added flexibility to change keyspace to the users

- charts/jaeger-operator/Chart.yaml
- charts/jaeger-operator/templates/deployment.yaml
- charts/jaeger-operator/templates/service-account.yaml
- charts/jaeger-operator/values.yaml
Signed-off-by: Lasse Højgaard <lho@trifork.com>
> jaeger-operator: add imagePullSecrets option.

- charts/jaeger/Chart.yaml
- charts/jaeger/README.md
- charts/jaeger/templates/collector-deploy.yaml
- charts/jaeger/templates/ingester-deploy.yaml
- charts/jaeger/templates/query-deploy.yaml
- charts/jaeger/values.yaml
Similar to keyspace in cassandra
> Added Elasticsearch indexPrefix option

- charts/jaeger-operator/Chart.yaml
- charts/jaeger-operator/templates/role.yaml
Add missing change from https://github.com/jaegertracing/jaeger-operator/commit/b6211a465568a11dcfd3b3ecf7ff16b30d8a9915.
Fixes #52.
> Grant kafka.strimzi.io rights

- charts/jaeger/Chart.yaml
- charts/jaeger/templates/query-deploy.yaml
So we can attach elatic search tls key for example
> support extraSecretMounts in query resource

- .github/workflows/release.yaml
Will merge as CI is currently broken.
> hotfix: v2 has depth 1 by default. That’s why no changes are detected.

- charts/jaeger/Chart.yaml
Signed-off-by: Naseem <naseem@transit.app>
> Bump chart to rerun release.

- charts/jaeger/Chart.yaml
- charts/jaeger/README.md
Signed-off-by: Jasstkn <jasssstkn@yahoo.com>
Open new PR due to problems with rebasing and sign off previous commits.
> Fixed: typo in README

- charts/jaeger-operator/Chart.yaml
- charts/jaeger-operator/templates/role.yaml
Adds autoscaling into  the operator roles
Fixes: https://github.com/jaegertracing/helm-charts/issues/68
Signed-off-by: Vipin Vijaykumar <vipin.vijaykumar@sap.com>
> [jaeger-operator] Add role permissions for AutoScaling

- charts/jaeger/Chart.yaml
- charts/jaeger/templates/_helpers.tpl
> fix: add missing newline when setting custom storage environment variables

- charts/jaeger-operator/Chart.yaml
- charts/jaeger-operator/README.md
- charts/jaeger-operator/values.yaml
- charts/jaeger/Chart.yaml
- charts/jaeger/README.md
- charts/jaeger/templates/collector-deploy.yaml
- charts/jaeger/templates/collector-svc.yaml
- charts/jaeger/values.yaml
https://github.com/jaegertracing/jaeger/releases/tag/v1.18.0
> Update Jaeger to 1.18.0, remove tchannel config

- charts/jaeger/Chart.yaml
- charts/jaeger/README.md
- charts/jaeger/templates/query-configmap.yaml
- charts/jaeger/templates/query-deploy.yaml
- charts/jaeger/values.yaml
Solves https://github.com/jaegertracing/helm-charts/issues/118
> Allow users to pass Query UI configuration in values.yaml file

- charts/jaeger/Chart.yaml
- charts/jaeger/values.yaml
> Resolving issue #153

- charts/jaeger-operator/Chart.yaml
- charts/jaeger-operator/crds/crd.yaml
- ct.yaml
Signed-off-by: Login Victor <batazor111@gmail.com>
- fixes #172
> [jaeger-operator] fix linter error

- charts/jaeger-operator/Chart.yaml
- charts/jaeger-operator/README.md
Signed-off-by: Login Victor <batazor111@gmail.com>
Updating minimal support version k8s
- fixes #187
> [jaeger-operator] update README file

- charts/jaeger/Chart.yaml
- charts/jaeger/values.yaml
Upgrades Jaeger version to 1.21.0
> [jaeger] Upgrade to v1.21.0 of Jaeger

- charts/jaeger/Chart.yaml
I'd like to nominate @mehta-ankit as a chart maintainer, he has been making steady contributions for some time.
@mehta-ankit if you are willing to take this up please approve this PR, however if you don't have the time/will it's not a problem we hope you continue to contribute.
@pavelnikolov @mikelorant @dvonthenen Would be nice to get at least one of your approvals.
Ankit will need to be added to the chart maintainers e-mail group.
> [jaeger] add mehta-ankit as a chart maintainer

- charts/jaeger/Chart.yaml
- charts/jaeger/templates/query-deploy.yaml
- charts/jaeger/values.yaml
Signed-off-by: santosh <bsantosh@thoughtworks.com>
Add support for configuring resources/limits in agent sidecar for jaeger query
- fixes # 282
> [jaeger] Add support for configuring resources/limits in agent sidecar for jaeger query

- charts/jaeger/Chart.yaml
- charts/jaeger/templates/agent-ds.yaml
- charts/jaeger/values.yaml
> [jaeger] Add initContainer option to agent daemonset.

- charts/jaeger/Chart.yaml
Upgrades appVersion to 1.30.0: https://github.com/jaegertracing/jaeger/releases/tag/v1.30.0v
N.A
> [Jaeger] Upgrade Jaeger App version for the chart

- charts/jaeger-operator/COMPATIBILITY.md
- charts/jaeger-operator/Chart.yaml
- charts/jaeger-operator/README.md
- charts/jaeger-operator/crds/crd.yaml
- charts/jaeger-operator/values.yaml
Signed-off-by: Micah Nagel <micah.nagel@parsons.com>
Fixes https://github.com/jaegertracing/helm-charts/issues/404
> [jaeger-operator] Update Jaeger Operator to 1.38.0

- charts/jaeger/Chart.yaml
Signed-off-by: Jared Tan <jian.tan@daocloud.io>
- fixes #
> [jaeger] bump up jaeger app version

- charts/jaeger/Chart.yaml
- charts/jaeger/templates/collector-hpa.yaml
- charts/jaeger/templates/ingester-hpa.yaml
- charts/jaeger/values.yaml
same as dynamic ingess version. this will allow k8s 1.25/1.26 deployments
> Add support for configurable hpa

- charts/jaeger/Chart.yaml
I want to use my personal email address instead of my previous work one.
> [jaeger] Change my email address

- charts/jaeger/Chart.yaml
> [jaeger] Upgrade jaeger appVersion gor chart

- charts/jaeger-operator/COMPATIBILITY.md
- charts/jaeger-operator/Chart.yaml
- charts/jaeger-operator/README.md
Updates Jaeger to the latest version.
Related to: #516
> [jaeger-operator] Update Jaeger version to latest

- index.yaml
Fixes the icon which is currently showing an error in Artifact Hub 
This might help us get the official badge, if not I have to ask that team for help.
https://github.com/jaegertracing/jaeger/issues/5363
- [NA] Chart Version bumped
- [NA] Title of the PR starts with chart name (`[jaeger]` or `[jaeger-operator]`)
- [NA] README.md has been updated to match version/contain new values
> Fix icon in index.yaml

- charts/jaeger/Chart.yaml
- charts/jaeger/templates/spark-cronjob.yaml
Fix jaeger spark job imagePullSecrets
> [jaeger] Fix jaeger spark job imagePullSecrets
